query me {
  me {
    code
     details
     message
     token
     item {
       id
       googleId
       email
       civilite
       firstname
       lastname
       updatedAt
       createdAt
     }
  }
}