query scrappingCarrefour {
  scrapingCarrefour {
    count
    carrefour {
      id
      label
      packaging
      price
      per_unit_label
      rayon_produits {
        rayon {
          code
          label
          slug
          level
        }
      }
      provider {
        label
      }
      produit_images {
        largest
      }
      produit_flags {
        label
      }
    }
  }
}